apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: halligalli-k3s-runtime
  namespace: argocd
  labels:
    app.kubernetes.io/name: halligalli-k3s-runtime
    app.kubernetes.io/part-of: halligalli-k3s
spec:
  project: halligalli-k3s
  source:
    repoURL: https://github.com/optiplex331/Halligalli-infrastructure.git
    targetRevision: main
    path: targets/k3s/gitops/runtime
    helm:
      valueFiles:
        - values/experiment.values.json
  destination:
    server: https://kubernetes.default.svc
    namespace: halligalli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
