version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: terraform
    directories:
      - /targets/aks/terraform
      - /targets/container-apps/terraform
      - /targets/k3s/terraform
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
