apiVersion: v1
kind: ServiceAccount
metadata:
  name: halligalli-observability
  labels:
    app.kubernetes.io/name: halligalli-observability
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: false
