apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: halligalli-observability-default-deny
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
