apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: halligalli-web
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: halligalli
      app.kubernetes.io/component: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: halligalli-api
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: halligalli
      app.kubernetes.io/component: api
