{{- range $component := list "web" "api" "redis" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: halligalli-{{ $component }}
  labels:
    {{- include "halligalli.labels" $ | nindent 4 }}
automountServiceAccountToken: false
---
{{- end }}
