{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: halligalli-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: "{{ .Values.ingress.tlsSecretName }}"
  issuerRef:
    name: "{{ .Values.tls.clusterIssuer }}"
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.ingress.host }}"
{{- end }}
