apiVersion: v1
kind: Service
metadata:
  name: halligalli-web
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: halligalli
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: halligalli-api
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: halligalli
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: halligalli-redis
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/name: halligalli
    app.kubernetes.io/component: redis
