apiVersion: v1
kind: ServiceAccount
metadata:
  name: halligalli-runtime
  labels:
    app.kubernetes.io/part-of: halligalli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: false
